/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutPage: typeof import('./src/components/AboutPage.vue')['default']
    BuyMeACoffee: typeof import('./src/components/BuyMeACoffee.vue')['default']
    HiddenGemsLogo: typeof import('./src/components/HiddenGemsLogo.vue')['default']
    LocationPointEditView: typeof import('./src/components/LocationPointEditView.vue')['default']
    LocationPointListView: typeof import('./src/components/LocationPointListView.vue')['default']
    LocationPointListViewDesktopWrapper: typeof import('./src/components/LocationPointListViewDesktopWrapper.vue')['default']
    LocationPointListViewMobileWrapper: typeof import('./src/components/LocationPointListViewMobileWrapper.vue')['default']
    LocationPointListViewWrapper: typeof import('./src/components/LocationPointListViewWrapper.vue')['default']
    Map: typeof import('./src/components/Map/Map.vue')['default']
    MapView: typeof import('./src/components/MapView.vue')['default']
    Navbar: typeof import('./src/components/Navbar/Navbar.vue')['default']
    NavbarDesktop: typeof import('./src/components/Navbar/NavbarDesktop.vue')['default']
    NavbarMobile: typeof import('./src/components/Navbar/NavbarMobile.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TermsOfService: typeof import('./src/components/TermsOfService.vue')['default']
  }
}
