const LOCATION_POINT_PREFIX = '/location-points'

export const LOCATION_POINT_PATHS = {
  GET_ALL: `${LOCATION_POINT_PREFIX}/get-all`,
  CREATE: `${LOCATION_POINT_PREFIX}/create`,
  UPDATE: `${LOCATION_POINT_PREFIX}/update`,
  GET_ROUTE: `${LOCATION_POINT_PREFIX}/get-route`,
  UPVOTE_POINT: `${LOCATION_POINT_PREFIX}/upvote`,
  REMOVE_UPVOTE_POINT: `${LOCATION_POINT_PREFIX}/remove-upvote`,
}
